Working on Makefiles:
  1. fix so default configuration ignores h4toh5lib, but builds
     hdf and hdf5, and object

  2. add 'src-dist' target

  3. Add 'VERSION', etc.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ echo > confdefs.h
 
 # A filename unique to this package, relative to the directory that
 # configure is in, which we can look for to find out if srcdir is correct.
-ac_unique_file=native/h4toh5lib/h4toh5Imp.c
+ac_unique_file=native/hdflib/hdfImp.c
 
 # Find the source files, if location was not specified.
 if test -z "$srcdir"; then
@@ -1855,7 +1855,7 @@ ac_cv_lib_HDF4INC=$HDF4INC
 
 ZLIB=$HDF4LIB"/libz.a"
 
-
+withval="";
  LIBHDF5=""
 # Check whether --with-hdf5 or --without-hdf5 was given.
 if test "${with_hdf5+set}" = set; then
@@ -1986,6 +1986,7 @@ ac_cv_lib_HDF5=$HDF5LIB
 ac_cv_lib_HDF5INC=$HDF5INC
 
 
+withval="";
  LIBH45=""
 # Check whether --with-h4toh5 or --without-h4toh5 was given.
 if test "${with_h4toh5+set}" = set; then
@@ -1998,31 +1999,34 @@ case "$withval" in
     { echo "configure: error: HDF 4 to 5 library needed for compilation." 1>&2; exit 1; }
     ;;
   no)
-    { echo "configure: error: HDF 4 to 5 library needed for compilation." 1>&2; exit 1; }
+    #AC_MSG_ERROR(HDF 4 to 5 library needed for compilation.)
+	H45LIB=""
+	H45INC=""
     ;;
   *)
-    hdf45_inc="`echo $withval |cut -f1 -d,`"
-    if test -n "$hdf45_inc"; then
-      HDF45INC="$hdf45_inc"
-      saved_CPPFLAGS="$CPPFLAGS"
-      CPPFLAGS="$CPPFLAGS -I$hdf45_inc"
-    fi
-
-    for ac_hdr in h4toh5public.h
+    if test -n "$withval"; then
+        hdf45_inc="`echo $withval |cut -f1 -d,`"
+        if test -n "$hdf45_inc"; then
+          HDF45INC="$hdf45_inc"
+          saved_CPPFLAGS="$CPPFLAGS"
+          CPPFLAGS="$CPPFLAGS -I$hdf45_inc"
+        fi
+    
+        for ac_hdr in h4toh5public.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:2016: checking for $ac_hdr" >&5
+echo "configure:2020: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2021 "configure"
+#line 2025 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2026: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2030: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2046,19 +2050,19 @@ EOF
 else
   echo "$ac_t""no" 1>&6
 CPPFLAGS="$saved_CPPFLAGS"
-                     { echo "configure: error: cannot find HDF45 header files!" 1>&2; exit 1; }
+                         { echo "configure: error: cannot find HDF45 header files!" 1>&2; exit 1; }
 fi
 done
 
-
-    hdf45_lib="`echo $withval | cut -f2 -d, -s`"
-
-    if test -n "$hdf45_lib"; then
-      HDF45LIB="$hdf45_lib"
-      saved_LDFLAGS="$LDFLAGS"
-      LDFLAGS="$LDFLAGS -L$hdf45_lib"
-      echo $ac_n "checking for H4toh5open in -lh4toh5""... $ac_c" 1>&6
-echo "configure:2062: checking for H4toh5open in -lh4toh5" >&5
+    
+        hdf45_lib="`echo $withval | cut -f2 -d, -s`"
+    
+        if test -n "$hdf45_lib"; then
+          HDF45LIB="$hdf45_lib"
+          saved_LDFLAGS="$LDFLAGS"
+          LDFLAGS="$LDFLAGS -L$hdf45_lib"
+          echo $ac_n "checking for H4toh5open in -lh4toh5""... $ac_c" 1>&6
+echo "configure:2066: checking for H4toh5open in -lh4toh5" >&5
 ac_lib_var=`echo h4toh5'_'H4toh5open | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2066,7 +2070,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lh4toh5  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2070 "configure"
+#line 2074 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2077,7 +2081,7 @@ int main() {
 H4toh5open()
 ; return 0; }
 EOF
-if { (eval echo configure:2081: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2085: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2103,11 +2107,12 @@ EOF
 else
   echo "$ac_t""no" 1>&6
 LDFLAGS="$saved_LDFLAGS"
-                 { echo "configure: error: cannot find HDF45 library." 1>&2; exit 1; }
+                     { echo "configure: error: cannot find HDF45 library." 1>&2; exit 1; }
 fi
 
-    else
-	 { echo "configure: error: cannot find HDF45 library path." 1>&2; exit 1; }
+        else
+    	 { echo "configure: error: cannot find HDF45 library path." 1>&2; exit 1; }
+        fi
     fi
     ;;
 esac
@@ -2145,17 +2150,17 @@ case "$withval" in
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:2149: checking for $ac_hdr" >&5
+echo "configure:2154: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2154 "configure"
+#line 2159 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2159: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2164: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2215,7 +2220,7 @@ JAVABIN="$JAVABIN/bin"
 # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2219: checking for $ac_word" >&5
+echo "configure:2224: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVA'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2250,7 +2255,7 @@ fi
 # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2254: checking for $ac_word" >&5
+echo "configure:2259: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2285,7 +2290,7 @@ fi
 # Extract the first word of "javadoc", so it can be a program name with args.
 set dummy javadoc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2289: checking for $ac_word" >&5
+echo "configure:2294: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVADOC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2320,7 +2325,7 @@ fi
 # Extract the first word of "jar", so it can be a program name with args.
 set dummy jar; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2324: checking for $ac_word" >&5
+echo "configure:2329: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2417,7 +2422,7 @@ fi
 JH45INST_FOUND=1
 if test -z "$JH45INST" ; then
 echo $ac_n "checking "JH45 install directory"""... $ac_c" 1>&6
-echo "configure:2421: checking "JH45 install directory"" >&5
+echo "configure:2426: checking "JH45 install directory"" >&5
 if eval "test \"`echo '$''{'ac_cv_lib_JH45INST'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2532,10 +2537,10 @@ esac
 
 
 
-#AC_SUBST_FILE(VERSION)
-#VERSION=./VERSION
-#VERSSTRING=`/bin/cat ./VERSION | sed -e 's/VERSION=JH45-//' `
-#AC_SUBST(VERSSTRING)
+
+VERSION=./VERSION
+VERSSTRING=`/bin/cat ./VERSION | sed -e 's/VERSION=HDF-JAVA-//' `
+
 
 
 trap '' 1 2 15
@@ -2737,6 +2742,9 @@ s%@JH45INST@%$JH45INST%g
 s%@JHVINST@%$JHVINST%g
 s%@JH5INST@%$JH5INST%g
 s%@ZLIB@%$ZLIB%g
+/@VERSION@/r $VERSION
+s%@VERSION@%%g
+s%@VERSSTRING@%$VERSSTRING%g
 
 CEOF
 EOF
